fix errors

diff --git a/.github/workflows/main.yaml b/.github/workflows/main.yaml
--- a/.github/workflows/main.yaml
+++ b/.github/workflows/main.yaml
@@ -60,9 +60,19 @@ jobs:
         run: |
           git config --global user.email "bot@blockscout.com"
           git config --global user.name "blockscout-bot"
+          git config pull.rebase true
+          git pull origin master
           git add .
           git commit -m "[BOT] [SKIP-GH-PAGES] Add index.html for new swagger.yaml files"
-          git push
+          git fetch origin master
+          
+          if git rebase origin/master; then
+            git push origin master
+          else
+            git rebase --abort
+            echo "Rebase failed due to conflicts, exiting."
+            exit 1
+          fi
 
       - name: Trigger github-pages workflow
         uses: actions/github-script@v4
